version: 0.2

phases:
  install:
    commands:
      - echo "Installing... nothing needed for this tiny app"
  build:
    commands:
      - echo "Running the app now"
      - python3 app.py
artifacts:
  files:
    - app.py
