version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Testing application..."
      - python3 app.py
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - app.py
    - appspec.yml
    - scripts/start.sh
